// cards.js - flashcard seed deck. [subject code, question, answer]  P=Physics C=Chemistry M=Maths
window.flashSeed = [
["P","Coulomb's law (magnitude)","F = k q₁q₂ / r², with k = 1/4πε₀ ≈ 9×10⁹ N·m²/C²"],
["P","Electric field of a point charge","E = kq / r², directed radially outward for +q"],
["P","Gauss's law","∮E·dA = q_enclosed / ε₀"],
["P","Capacitance of a parallel-plate capacitor","C = ε₀A/d (with a dielectric filling it: C = Kε₀A/d)"],
["P","Energy stored in a capacitor","U = ½CV² = Q²/2C = ½QV"],
["P","Potential due to a point charge","V = kq / r (a scalar)"],
["P","Relation between E and V","E = −dV/dr"],
["P","Capacitors in series and parallel","Series: 1/C = Σ1/Cᵢ. Parallel: C = ΣCᵢ"],
["P","Drift velocity","v_d = I / (nAe)"],
["P","Ohm's law and resistivity","V = IR and R = ρl/A"],
["P","Kirchhoff's laws","KCL: ΣI = 0 at a junction. KVL: ΣV = 0 around a closed loop"],
["P","Biot–Savart law","dB = (μ₀/4π) · I dl × r̂ / r²"],
["P","Magnetic field of a long straight wire","B = μ₀I / (2πr)"],
["P","Lorentz force","F = q(E + v × B)"],
["P","Faraday's law of induction","ε = −dΦ/dt"],
["P","Energy stored in an inductor","U = ½LI²"],
["P","RMS values in AC","I_rms = I₀/√2 and V_rms = V₀/√2"],
["P","Impedance of a series LCR circuit; resonance","Z = √(R² + (X_L − X_C)²); resonance at ω = 1/√(LC)"],
["P","Lens maker's formula","1/f = (n − 1)(1/R₁ − 1/R₂)"],
["P","Lens formula (Cartesian sign convention)","1/v − 1/u = 1/f"],
["P","Fringe width in Young's double slit","β = λD / d"],
["P","Einstein's photoelectric equation","KE_max = hν − φ"],
["P","de Broglie wavelength","λ = h/p = h/mv"],
["P","Bohr model: hydrogen energy levels and radii","Eₙ = −13.6 eV / n²; rₙ ≈ 0.529 n² Å"],
["P","Radioactive decay law and half-life","N = N₀e^(−λt); T½ = 0.693/λ"],
["P","Newton's second law (momentum form)","F = dp/dt"],
["P","Escape velocity","v_e = √(2GM/R) ≈ 11.2 km/s for Earth"],
["P","Time period of a spring-mass system and a simple pendulum","T = 2π√(m/k); T = 2π√(l/g)"],
["P","Work–energy theorem","W_net = ΔKE"],
["P","Moments of inertia: ring, disc, solid sphere","Ring (axis ⟂ plane) MR²; disc ½MR²; solid sphere (diameter) (2/5)MR²"],
["P","Bernoulli's equation","P + ½ρv² + ρgh = constant"],
["P","First law of thermodynamics","ΔU = Q − W"],
["P","Adiabatic process relation","PV^γ = constant, where γ = Cp/Cv"],
["P","RMS speed of gas molecules","v_rms = √(3RT/M)"],
["P","Snell's law","n₁ sinθ₁ = n₂ sinθ₂"],
["C","Mole concept relations","moles = mass / molar mass = N / N_A, with N_A = 6.022×10²³"],
["C","Ideal gas equation and R","PV = nRT; R = 0.0821 L·atm/mol·K = 8.314 J/mol·K"],
["C","Heisenberg uncertainty principle","Δx · Δp ≥ h/4π"],
["C","Rydberg formula for hydrogen spectrum","1/λ = R_H (1/n₁² − 1/n₂²), R_H ≈ 1.097×10⁷ m⁻¹"],
["C","The four quantum numbers","n (shell), l (0 to n−1), m_l (−l to +l), m_s (±½)"],
["C","Aufbau, Hund and Pauli rules","Aufbau: fill lowest energy first. Hund: maximise unpaired spins in degenerate orbitals. Pauli: no two electrons share all four quantum numbers"],
["C","Bond order from MO theory","(Nb − Na) / 2"],
["C","Hybridisation and shape of SF₆ and XeF₄","SF₆: sp³d², octahedral. XeF₄: sp³d², square planar"],
["C","Relation between ΔH and ΔU","ΔH = ΔU + Δn_g RT"],
["C","Gibbs energy and spontaneity","ΔG = ΔH − TΔS; spontaneous when ΔG < 0; ΔG° = −RT ln K"],
["C","Hess's law","Total enthalpy change depends only on initial and final states, not the path"],
["C","Relation between Kp and Kc","Kp = Kc (RT)^Δn"],
["C","pH and pOH","pH = −log[H⁺]; at 25 °C, pH + pOH = 14"],
["C","Henderson–Hasselbalch equation (acidic buffer)","pH = pKa + log([salt]/[acid])"],
["C","Ksp for a salt AₓB_y","Ksp = (xs)ˣ (ys)ʸ, where s is the molar solubility"],
["C","Nernst equation at 298 K","E = E° − (0.0591/n) log Q"],
["C","Relation between ΔG° and cell EMF","ΔG° = −nFE°"],
["C","Faraday's first law of electrolysis","m = ZIt = (M/nF) · It"],
["C","First-order rate constant and half-life","k = (2.303/t) log([A]₀/[A]); t½ = 0.693/k"],
["C","Arrhenius equation","k = A e^(−Ea/RT)"],
["C","Raoult's law","p_A = x_A · p°_A"],
["C","Colligative property formulas","ΔT_b = i K_b m; ΔT_f = i K_f m; π = iCRT"],
["C","Spin-only magnetic moment","μ = √(n(n+2)) BM, n = number of unpaired electrons"],
["C","SN1 versus SN2","SN2: bimolecular, one step, inversion, favoured by 1° halides. SN1: unimolecular, carbocation, racemisation, favoured by 3°"],
["C","Markovnikov's rule","In HX addition to an alkene, H goes to the carbon already holding more H atoms (more stable carbocation forms)"],
["C","Grignard reagent with carbonyls","With HCHO gives 1° alcohol; other aldehydes give 2°; ketones give 3° alcohols"],
["C","Hoffmann bromamide reaction","RCONH₂ + Br₂ + 4NaOH → RNH₂ + Na₂CO₃ + 2NaBr + 2H₂O (amine has one carbon less)"],
["C","Aldol condensation","Carbonyls with α-H, dilute base → β-hydroxy carbonyl, then α,β-unsaturated carbonyl on heating"],
["C","Cannizzaro reaction","Aldehydes with no α-H in conc. alkali → alcohol + carboxylate (disproportionation)"],
["C","Tollens' test","Aldehydes give a silver mirror; ketones do not"],
["C","Hückel's rule","Planar, cyclic, fully conjugated with (4n + 2) π electrons → aromatic"],
["C","Maximum stereoisomers","With n different stereocentres: up to 2ⁿ stereoisomers"],
["C","Lanthanoid contraction","Gradual decrease in ionic radius from La³⁺ to Lu³⁺ due to poor shielding by 4f electrons"],
["C","Ionisation energy trend","Increases across a period, decreases down a group (exceptions: Be > B, N > O)"],
["C","Molarity versus molality","Molarity = mol solute / L solution (temperature dependent). Molality = mol solute / kg solvent (not)"],
["M","Roots of a quadratic","x = (−b ± √(b² − 4ac)) / 2a; sum = −b/a; product = c/a"],
["M","Nature of roots from discriminant","D > 0 real and distinct; D = 0 real and equal; D < 0 complex conjugates"],
["M","AP: nth term and sum","aₙ = a + (n−1)d; Sₙ = (n/2)[2a + (n−1)d]"],
["M","GP: nth term, sum, infinite sum","aₙ = arⁿ⁻¹; Sₙ = a(rⁿ−1)/(r−1); S∞ = a/(1−r) for |r| < 1"],
["M","AM–GM inequality","For positive numbers, AM ≥ GM, with equality when all are equal"],
["M","General term of binomial expansion","T_{r+1} = ⁿC_r · aⁿ⁻ʳ · bʳ"],
["M","Permutations and combinations","ⁿP_r = n!/(n−r)!; ⁿC_r = n!/(r!(n−r)!)"],
["M","Sum of binomial coefficients","ΣⁿC_r = 2ⁿ"],
["M","Euler's formula","e^(iθ) = cosθ + i sinθ"],
["M","Modulus and conjugate relation","z · z̄ = |z|²"],
["M","De Moivre's theorem","(cosθ + i sinθ)ⁿ = cos nθ + i sin nθ"],
["M","Cube roots of unity","1 + ω + ω² = 0 and ω³ = 1"],
["M","sin(A + B)","sinA cosB + cosA sinB"],
["M","cos 2A (three forms)","cos²A − sin²A = 2cos²A − 1 = 1 − 2sin²A"],
["M","tan(A + B)","(tanA + tanB) / (1 − tanA tanB)"],
["M","sin 3A","3 sinA − 4 sin³A"],
["M","Principal value ranges","sin⁻¹: [−π/2, π/2]; cos⁻¹: [0, π]; tan⁻¹: (−π/2, π/2)"],
["M","Standard limits at 0","sin x / x → 1; (eˣ − 1)/x → 1; (1 + x)^(1/x) → e"],
["M","Product rule","d/dx (uv) = u′v + uv′"],
["M","Derivatives of tan x and sec x","d/dx tan x = sec²x; d/dx sec x = sec x tan x"],
["M","Basic integrals of 1/x and eˣ","∫1/x dx = ln|x| + C; ∫eˣ dx = eˣ + C"],
["M","∫ dx / (a² + x²)","(1/a) tan⁻¹(x/a) + C"],
["M","∫ dx / √(a² − x²)","sin⁻¹(x/a) + C"],
["M","Integration by parts and ILATE","∫u v dx = u∫v dx − ∫(u′ ∫v dx) dx; choose u by ILATE (Inverse, Log, Algebraic, Trig, Exponential)"],
["M","King's property of definite integrals","∫₀ᵃ f(x) dx = ∫₀ᵃ f(a − x) dx"],
["M","Even and odd functions over [−a, a]","2∫₀ᵃ f dx if f is even; 0 if f is odd"],
["M","Linear differential equation","dy/dx + Py = Q; IF = e^(∫P dx); y · IF = ∫Q · IF dx + C"],
["M","Distance from a point to a line","|Ax₁ + By₁ + C| / √(A² + B²)"],
["M","Circle: equations and radius","(x−h)² + (y−k)² = r²; general form x² + y² + 2gx + 2fy + c = 0 with r = √(g² + f² − c)"],
["M","Parabola y² = 4ax","Focus (a, 0), directrix x = −a, latus rectum 4a"],
["M","Ellipse x²/a² + y²/b² = 1","e = √(1 − b²/a²); foci (±ae, 0)"],
["M","Hyperbola x²/a² − y²/b² = 1","e = √(1 + b²/a²); asymptotes y = ±(b/a)x"],
["M","Dot and cross product magnitudes","a·b = |a||b| cosθ; |a × b| = |a||b| sinθ"],
["M","Scalar triple product","[a b c] = a·(b × c) = volume of the parallelepiped"],
["M","Determinant and adjoint properties","|AB| = |A||B|; |kA| = kⁿ|A| for n×n; A · adj A = |A| I"],
["M","Inverse of a matrix","A⁻¹ = adj(A) / |A|"],
["M","Bayes' theorem","P(Eᵢ|A) = P(Eᵢ)P(A|Eᵢ) / Σⱼ P(Eⱼ)P(A|Eⱼ)"],
["M","Binomial distribution","P(X = r) = ⁿC_r pʳ qⁿ⁻ʳ; mean np; variance npq"],
["M","Distance between skew lines","|(a₂ − a₁)·(b₁ × b₂)| / |b₁ × b₂|"],
["M","Angle between two lines in 3D","cosθ = |a₁a₂ + b₁b₂ + c₁c₂| / (√(a₁²+b₁²+c₁²) · √(a₂²+b₂²+c₂²))"]
];
