// data.js - Lectures and Files Library

window.rawLectures = [
    {
    "title": "Physics One-Shots (PW)",
    "folders": ["LECTURES", "Physics", "Physics Wallah"],
    "playlist": [
        { "title": "Basic Maths & Vectors", "url": "https://www.youtube.com/embed/RAwcPN79g0Q" },
        { "title": "Kinematics", "url": "https://www.youtube.com/embed/mpFEnSQpJ9Q" },
        { "title": "Laws of Motion", "url": "https://www.youtube.com/embed/6HQgDO1trlM" },
        { "title": "Work, Energy & Power", "url": "https://www.youtube.com/embed/XGce-vIcMfU" },
        { "title": "COM & Collision", "url": "https://www.youtube.com/embed/Rh95KkMwklU" },
        { "title": "Rotational Motion", "url": "https://www.youtube.com/embed/vmaKeSkjtGo" },
        { "title": "Gravitation", "url": "https://www.youtube.com/embed/mE8w2uxm6XY" },
        { "title": "Solids & Elasticity", "url": "https://www.youtube.com/embed/1xPm3vIRIGI" },
        { "title": "Fluid Mechanics", "url": "https://www.youtube.com/embed/griSf2U_Zlk" },
        { "title": "SHM", "url": "https://www.youtube.com/embed/myNQbAYzD5A" },
        { "title": "Wave Motion", "url": "https://www.youtube.com/embed/PAlXOkn_Pa8" },
        { "title": "Thermal Properties", "url": "https://www.youtube.com/embed/1nTFrbJ8Jhg" },
        { "title": "Thermodynamics & KTG", "url": "https://www.youtube.com/embed/Ch9jLsgYIuM" },
        { "title": "Electrostatics", "url": "https://www.youtube.com/embed/h5HIyPNRhqI" },
        { "title": "Capacitors", "url": "https://www.youtube.com/embed/FImh-a0673s" },
        { "title": "Current Electricity", "url": "https://www.youtube.com/embed/cjoRcywyRv0" },
        { "title": "Magnetism & Moving Charges", "url": "https://www.youtube.com/embed/3h3OexznsA0" },
        { "title": "Electromagnetic Induction", "url": "https://www.youtube.com/embed/ebOF14qP21k" },
        { "title": "AC Circuits", "url": "https://www.youtube.com/embed/gziRcxMiO_Q" },
        { "title": "Wave Optics & EM Waves", "url": "https://www.youtube.com/embed/UYfR15GpKIs" },
        { "title": "Ray Optics", "url": "https://www.youtube.com/embed/AfPD-sHayb0" },
        { "title": "Semiconductors", "url": "https://www.youtube.com/embed/5h5ANJnVe08" },
        { "title": "Communication Systems", "url": "https://www.youtube.com/embed/fBqJdix2NjE" },
        { "title": "Modern Physics", "url": "https://www.youtube.com/embed/G58QS4soCuQ" },
        { "title": "Atoms", "url": "https://www.youtube.com/embed/AqjrqRyot6w" },
        { "title": "Nuclei", "url": "https://www.youtube.com/embed/XJZ1PdXyJU4" },
        { "title": "Dual Nature", "url": "https://www.youtube.com/embed/wE0xrUuJLnk" }
    ]
    },
    {
    "title": "Physical Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "playlist": [
        { "title": "Mole Concept", "url": "https://www.youtube.com/embed/CAb8YZKLoac" },
        { "title": "Atomic Structure", "url": "https://www.youtube.com/embed/f6ENSghG7T4" },
        { "title": "States of Matter", "url": "https://www.youtube.com/embed/8oypjDXAXZc" },
        { "title": "Thermodynamics", "url": "https://www.youtube.com/embed/GplPceRaMi0" },
        { "title": "Chemical Equilibrium", "url": "https://www.youtube.com/embed/NwCmoh7Vd9g" },
        { "title": "Ionic Equilibrium", "url": "https://www.youtube.com/embed/BceSksiNLD4" },
        { "title": "Redox Reactions", "url": "https://www.youtube.com/embed/1W-UvePUAKo" },
        { "title": "Chemical Kinetics", "url": "https://www.youtube.com/embed/kwPNxC9AgZA" },
        { "title": "Solutions", "url": "https://www.youtube.com/embed/7OkNy8vhDaw" }
    ]
    },
    {
    "title": "Inorganic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "playlist": [
        { "title": "Periodic Table", "url": "https://www.youtube.com/embed/nLE7_YBFQNQ" },
        { "title": "Chemical Bonding", "url": "https://www.youtube.com/embed/kS8s_WX0IlY" },
        { "title": "Coordination Compounds", "url": "https://www.youtube.com/embed/5myJzBeN514" },
        { "title": "P-Block Elements", "url": "https://www.youtube.com/embed/b0k5LOk_uPk" },
        { "title": "D & F-Block Elements", "url": "https://www.youtube.com/embed/SjILQ6cX_Vo" },
        { "title": "Salt Analysis", "url": "https://www.youtube.com/embed/8rRnn4ECwXI" }
    ]
    },
    {
    "title": "Organic Chemistry (PW)",
    "folders": ["LECTURES", "Chemistry", "Physics Wallah"],
    "playlist": [
        { "title": "IUPAC Nomenclature", "url": "https://www.youtube.com/embed/A2QTsYu3fWo" },
        { "title": "GOC", "url": "https://www.youtube.com/embed/FFCT-lh86tA" },
        { "title": "Isomerism", "url": "https://www.youtube.com/embed/UOzWO2-Z9So" },
        { "title": "Hydrocarbons", "url": "https://www.youtube.com/embed/02CBTEOMMsA" },
        { "title": "Haloalkanes & Haloarenes", "url": "https://www.youtube.com/embed/7iJFvPI8vMM" },
        { "title": "Alcohols, Phenols & Ethers", "url": "https://www.youtube.com/embed/IDo8B0c5Xis" },
        { "title": "Aldehydes, Ketones & Acids", "url": "https://www.youtube.com/embed/oR19BqbPBu4" },
        { "title": "Amines", "url": "https://www.youtube.com/embed/SKHrfD34Kkc" },
        { "title": "Biomolecules", "url": "https://www.youtube.com/embed/LcVNwEWJtyI" }
    ]
    },
    {
    "title": "Mathematics (PW)",
    "folders": ["LECTURES", "Maths", "Physics Wallah"],
    "playlist": [
        { "title": "Basic Maths", "url": "https://www.youtube.com/embed/Z5uGIO_11vM" },
        { "title": "Determinants", "url": "https://www.youtube.com/embed/uhq_WUNlvh8" },
        { "title": "Trigonometric Ratios & Identities", "url": "https://www.youtube.com/embed/DitLpxy6V48" },
        { "title": "Vectors", "url": "https://www.youtube.com/embed/FsTlbTQyuJ0" },
        { "title": "Quadratic Equations", "url": "https://www.youtube.com/embed/iLIPlvjDkPU" },
        { "title": "Matrices", "url": "https://www.youtube.com/embed/2YFQIFQmPmw" },
        { "title": "Sets", "url": "https://www.youtube.com/embed/SOXQuRrgJHo" },
        { "title": "3D Geometry", "url": "https://www.youtube.com/embed/t_RMMkiYj4g" },
        { "title": "Sequence & Series", "url": "https://www.youtube.com/embed/CVG9PcraP1k" },
        { "title": "Relations & Functions", "url": "https://www.youtube.com/embed/Qs0wRt70mC4" },
        { "title": "Inverse Trigonometric Functions", "url": "https://www.youtube.com/embed/rdWRwY2kEXI" },
        { "title": "Permutation & Combination", "url": "https://www.youtube.com/embed/rPFlUfjcakw" },
        { "title": "Binomial Theorem", "url": "https://www.youtube.com/embed/QMWDHOcXEQI" },
        { "title": "Method of Differentiation", "url": "https://www.youtube.com/embed/3JMzZR2TvhA" },
        { "title": "Straight Lines", "url": "https://www.youtube.com/embed/pufR8xp-CQA" },
        { "title": "Indefinite Integration", "url": "https://www.youtube.com/embed/7dVDuyI_8FA" },
        { "title": "Circles", "url": "https://www.youtube.com/embed/qcpj3jjgr6o" },
        { "title": "Parabola", "url": "https://www.youtube.com/embed/Nv9s38ZGPes" },
        { "title": "Definite Integration", "url": "https://www.youtube.com/embed/UwRAUIeoCtI" },
        { "title": "Differential Equation", "url": "https://www.youtube.com/embed/H1FKKjz8hsw" },
        { "title": "Hyperbola", "url": "https://www.youtube.com/embed/zITyahKONeg" },
        { "title": "Application of Integrals", "url": "https://www.youtube.com/embed/x0vMQRKTmQ0" },
        { "title": "Ellipse", "url": "https://www.youtube.com/embed/ZdCd1G0NDUI" },
        { "title": "Complex Number", "url": "https://www.youtube.com/embed/Q-AlaLN72w0" },
        { "title": "Limits", "url": "https://www.youtube.com/embed/JnER25G1V7o" },
        { "title": "Statistics", "url": "https://www.youtube.com/embed/mWa7eSpT6kg" },
        { "title": "Probability", "url": "https://www.youtube.com/embed/3OFuYbk-BV4" },
        { "title": "Continuity & Differentiability", "url": "https://www.youtube.com/embed/hsedtF2azNQ" },
        { "title": "Application of Derivatives", "url": "https://www.youtube.com/embed/jOVcucQLv38" }
    ]
    },
    {
    "title": "JEE Maths Playlist 1 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
        { "title": "Sequences & Series 3.0", "url": "https://www.youtube.com/embed/VMlrlqJgWdQ" },
        { "title": "Matrices & Determinants 3.0", "url": "https://www.youtube.com/embed/QIbRBtoAsjE" },
        { "title": "Vectors & 3D Geometry 3.0", "url": "https://www.youtube.com/embed/QWo-Uy7KRp4" },
        { "title": "Calculus Booster Sprint", "url": "https://www.youtube.com/embed/K8fyaYIGtBE" },
        { "title": "Complex Numbers 3.0", "url": "https://www.youtube.com/embed/XVZ20FDLorE" },
        { "title": "Quadratic Equations 3.0", "url": "https://www.youtube.com/embed/MnUt4uRiUv8" },
        { "title": "Binomial Theorem 3.0", "url": "https://www.youtube.com/embed/kTrZgk8ht6s" },
        { "title": "Functions 3.0", "url": "https://www.youtube.com/embed/qMZbl49B2gk" },
        { "title": "Limits, Continuity & Derivatives 3.0", "url": "https://www.youtube.com/embed/1Px2H-ZNAXc" },
        { "title": "Application of Derivatives 3.0", "url": "https://www.youtube.com/embed/FjePwtMW_jA" },
        { "title": "Indefinite Integration 3.0", "url": "https://www.youtube.com/embed/aBuT_NpL4kM" },
        { "title": "Definite Integration 3.0", "url": "https://www.youtube.com/embed/bpeEpWjvG50" },
        { "title": "Differential Equations 3.0", "url": "https://www.youtube.com/embed/PbeylmdToTs" },
        { "title": "Sets & Relations 3.0", "url": "https://www.youtube.com/embed/BbDh_D9NOAc" },
        { "title": "Permutations & Combinations 3.0", "url": "https://www.youtube.com/embed/dZleU5ZUDAo" },
        { "title": "Probability 3.0", "url": "https://www.youtube.com/embed/N1gW3lZx_4I" },
        { "title": "Straight Lines 3.0", "url": "https://www.youtube.com/embed/RHk11VC256Y" },
        { "title": "Circles 3.0", "url": "https://www.youtube.com/embed/Se39Hv2_FzM" },
        { "title": "Conic Sections One Shot", "url": "https://www.youtube.com/embed/ze6pUWYfAvY" },
        { "title": "Inverse Trigonometry 3.0", "url": "https://www.youtube.com/embed/EO_6mXn9szs" },
        { "title": "Statistics 3.0", "url": "https://www.youtube.com/embed/WFY1D61ZOV0" },
        { "title": "Trigonometry & Inverse Trigonometry 3.0", "url": "https://www.youtube.com/embed/IQeeRDA6T94" },
        { "title": "Make Your Math Superstrong Topics", "url": "https://www.youtube.com/embed/fvUETQWW34Y" },
        { "title": "Differential Equations & Area Under Curve", "url": "https://www.youtube.com/embed/KGI1PiPN-q4" },
        { "title": "5 Easiest Chapters Math Marathon Part 1", "url": "https://www.youtube.com/embed/p3R5yXcJdX4" },
        { "title": "5 Easiest Chapters Math Marathon Part 2", "url": "https://www.youtube.com/embed/q44atF--01U" },
        { "title": "Complete Formula Revision Class 11", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
        { "title": "Complete Formula Revision Class 12", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
        { "title": "Math Super Shortcuts & Tricks", "url": "https://www.youtube.com/embed/tVN2lZQV2_M" },
        { "title": "JEE Jan '24 PYQs with Shortcuts", "url": "https://www.youtube.com/embed/XHDRIk0UL0w" },
        { "title": "15 Sureshot Topics Math Marathon", "url": "https://www.youtube.com/embed/Zl53W-m0wTM" },
        { "title": "65 Topics (High Priority) for 99.5%ile", "url": "https://www.youtube.com/embed/hhLxKrIj5b4" },
        { "title": "JEE 2025 Final Push Game Changer", "url": "https://www.youtube.com/embed/WPQzDvdJQak" },
        { "title": "Code 301: Save Your 1st Attempt", "url": "https://www.youtube.com/embed/IqiClz6TEiM" },
        { "title": "Vectors & 3D Booster Sprint", "url": "https://www.youtube.com/embed/hezQFC6RJjs" },
        { "title": "Algebra Revision Sprint", "url": "https://www.youtube.com/embed/LLxVhlleHRM" },
        { "title": "Coordinate Geometry Revision Sprint", "url": "https://www.youtube.com/embed/csb-IQN_pqU" },
        { "title": "60 Most Repeated Ques by NTA", "url": "https://www.youtube.com/embed/FgILOHipMtw" },
        { "title": "JEE Jan 2025 Math Marathon", "url": "https://www.youtube.com/embed/D0hzgpe5L9s" },
        { "title": "JEE Apr 2025 Analysis of All 10 Shifts", "url": "https://www.youtube.com/embed/Wr6MNW6itqo" }
    ]
    },
    {
    "title": "JEE Maths Playlist 2 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
        { "title": "Agni Series: Sequences & Series", "url": "https://www.youtube.com/embed/AVjdJITX0Nc" },
        { "title": "Agni Series: Matrices & Determinants", "url": "https://www.youtube.com/embed/obx33lta9P4" },
        { "title": "Agni Series: Vectors & 3D Geometry", "url": "https://www.youtube.com/embed/Ui0P-tOC-f0" },
        { "title": "Agni Series: Quadratic Equations & Complex Nos", "url": "https://www.youtube.com/embed/pouyY30rSHo" },
        { "title": "Agni Series: Binomial Theorem", "url": "https://www.youtube.com/embed/IKZ_2Z2OOBQ" },
        { "title": "Agni Series: Permutations & Combinations + Probability", "url": "https://www.youtube.com/embed/--k01m3f5Cw" },
        { "title": "Agni Series: Sets, Relations & Functions", "url": "https://www.youtube.com/embed/7HbfPG8pVhs" },
        { "title": "Agni Series: Trigonometry & Statistics", "url": "https://www.youtube.com/embed/2DC7cdv43Ao" },
        { "title": "Agni Series: Limits, Continuity & Derivatives + AOD", "url": "https://www.youtube.com/embed/ryAw6vipopk" },
        { "title": "Agni Series: Integration", "url": "https://www.youtube.com/embed/mjoCuNKUzB4" },
        { "title": "Agni Series: Differential Equations & Area", "url": "https://www.youtube.com/embed/aSAg23ixuWE" },
        { "title": "Agni Series: Straight Lines & Circles", "url": "https://www.youtube.com/embed/2eOXSPy1MuE" },
        { "title": "Agni Series: Conic Sections", "url": "https://www.youtube.com/embed/4vagx7oH87k" },
        { "title": "100 Days Timetable for JEE 2026", "url": "https://www.youtube.com/embed/aIjPAFSjRcI" },
        { "title": "Agni Series: Sequences & Series (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/0DJXH0ql7BI" },
        { "title": "Agni Series: Matrices & Determinants (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/JdHwa70kY3s" },
        { "title": "Agni Series: Trigonometry & Inverse + Statistics (Jan 2025)", "url": "https://www.youtube.com/embed/qcDGzbWSTjo" },
        { "title": "Agni Series: Sets, Relations & Functions (Jan 2025)", "url": "https://www.youtube.com/embed/o07B71pxaBo" },
        { "title": "Agni Series: Complex Numbers & Quadratic Eqns (Jan 2025)", "url": "https://www.youtube.com/embed/EJtgkGdqOgY" },
        { "title": "Agni Series: Permutations & Combinations + Probability (Jan 2025)", "url": "https://www.youtube.com/embed/jUxPvBZAK_4" },
        { "title": "Agni Series: Binomial Theorem (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/56Odj-FzH18" },
        { "title": "Agni Series: Limits, Continuity & Derivatives (Jan 2025)", "url": "https://www.youtube.com/embed/PTO6XHJfFU8" },
        { "title": "Agni Series: AOD & Area Under Curve (Jan 2025)", "url": "https://www.youtube.com/embed/yMiEhnxQe8Y" },
        { "title": "Agni Series: Integration (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/dgUEfZohNJU" },
        { "title": "Agni Series: Vectors (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/UI_SOsUZBJE" },
        { "title": "Agni Series: 3D Geometry (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/FJia0zLEq4U" },
        { "title": "Agni Series: Straight Lines (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/Me9E0PFbuGQ" },
        { "title": "Agni Series: Parabola (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/feBdaVYlkNs" },
        { "title": "Agni Series: Circles, Ellipse & Hyperbola (Jan 2025 PYQs)", "url": "https://www.youtube.com/embed/kHj73PtXHQE" },
        { "title": "Complete Formula Revision Class 12", "url": "https://www.youtube.com/embed/yZhWIgH-wqs" },
        { "title": "Complete Formula Revision Class 11", "url": "https://www.youtube.com/embed/H3ajZU-w1Mk" },
        { "title": "100 Most Repeated Math PYQs Last 7 Years", "url": "https://www.youtube.com/embed/FZJt1h-gO4w" },
        { "title": "Booster: 7 Easiest Chapters = 36+ Marks", "url": "https://www.youtube.com/embed/mcMHaUuhe6o" },
        { "title": "Booster: 67 Most Asked Topics by NTA", "url": "https://www.youtube.com/embed/UNOBGZjYiFk" },
        { "title": "Booster: 6 Highest Weightage Chapters = 48+ Marks", "url": "https://www.youtube.com/embed/mb_ZpNpL4Go" },
        { "title": "Math Marathon: Most Trending Topics & PYQs", "url": "https://www.youtube.com/embed/v8qnbEQulmA" },
        { "title": "100 Most Asked Questions by NTA", "url": "https://www.youtube.com/embed/vMGMYl00kJI" }
    ]
    },
    {
    "title": "JEE Maths Playlist 3 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
        { "title": "Logarithms | Beginner's Course", "url": "https://www.youtube.com/embed/j1pDmQJ0wOY" },
        { "title": "Trigonometry | Beginner's Course", "url": "https://www.youtube.com/embed/nfPvo7p-8t0" },
        { "title": "Inequalities : Wavy Curve | Beginner's Course", "url": "https://www.youtube.com/embed/F0eIeAYiUUM" },
        { "title": "Functions Basics, Domain & Range | Beginner's Course", "url": "https://www.youtube.com/embed/GNtYHAk_C4s" },
        { "title": "Modulus & Greatest Integer Functions | Beginner's Course", "url": "https://www.youtube.com/embed/Q1AMRktu4pc" },
        { "title": "Transformation of Graphs | Beginner's Course", "url": "https://www.youtube.com/embed/V3PYBhJS0Po" },
        { "title": "Complex Numbers | Beginner's Course", "url": "https://www.youtube.com/embed/0Bul5m9fN_8" },
        { "title": "Sequences & Series | Beginner's Course", "url": "https://www.youtube.com/embed/AmUO2o9NOYk" },
        { "title": "Limits with Tricks | Beginner's Course", "url": "https://www.youtube.com/embed/WvmEDNxgVxg" },
        { "title": "Differentiation | Beginner's Course", "url": "https://www.youtube.com/embed/KUu18_pkvbk" },
        { "title": "Integration | Beginner's Course", "url": "https://www.youtube.com/embed/C3DS0tqK2TY" },
        { "title": "Vectors | Beginner's Course", "url": "https://www.youtube.com/embed/BPgL5Xrp1LA" },
        { "title": "Matrices and Determinants | Beginner's Course", "url": "https://www.youtube.com/embed/lkAPODbXnS0" },
        { "title": "Binomial Theorem | Beginner's Course", "url": "https://www.youtube.com/embed/Bk6PQ6huy68" },
        { "title": "Permutations and Combinations | Beginner's Course", "url": "https://www.youtube.com/embed/Sh6yppz4nzs" },
        { "title": "Probability | Beginner's Course", "url": "https://www.youtube.com/embed/HkBKPCNFZ4k" },
        { "title": "Straight Lines | Beginner's Course", "url": "https://www.youtube.com/embed/QS59lEJgPb8" },
        { "title": "Conic Sections | Beginner's Course", "url": "https://www.youtube.com/embed/u4Fu2PcRSo4" },
        { "title": "Quadratic Equations | Beginner's Course", "url": "https://www.youtube.com/embed/_P2GRAVyk_Q" },
        { "title": "Sets | Beginner's Course", "url": "https://www.youtube.com/embed/LK0cQmgJsdk" },
        { "title": "Relations | Beginner's Course", "url": "https://www.youtube.com/embed/MvTfxcM8hHs" },
        { "title": "3D Geometry | Beginner's Course", "url": "https://www.youtube.com/embed/fdfT1w9rVJQ" }
    ]
    },
    {
    "title": "JEE Maths Playlist 4 - Neha Ma'am",
    "folders": ["LECTURES", "Maths", "Neha Agrawal"],
    "playlist": [
        { "title": "Differentiation | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/ct-vCt9NU08" },
        { "title": "Logarithms | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/cJceE7-8TBY" },
        { "title": "Linear Inequalities & Wavy Curve | Foundation Series", "url": "https://www.youtube.com/embed/UJXel5_AOSY" },
        { "title": "Trigonometry | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/GN9uAEisDtM" },
        { "title": "Functions - Domain & Range | Foundation Series", "url": "https://www.youtube.com/embed/peKwXDIcYss" },
        { "title": "Integration | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/iaK4ukVmFvc" },
        { "title": "Sequences and Series | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/yP0EKKN0zys" },
        { "title": "Probability | Class 11 Foundation Series", "url": "https://www.youtube.com/embed/7_ZpO1hneXk" },
        { "title": "Complete Class 11 Maths Required for Class 12 & JEE", "url": "https://www.youtube.com/embed/TQX02-rVCsA" }
    ]
    },
    {
    "title": "Eduniti Physics Sure Shot",
    "folders": ["LECTURES", "Physics", "Eduniti"],
    "playlist": [
        { "title": "Kinematics 2D", "url": "https://www.youtube.com/embed/_d0XU35l5jY" },
        { "title": "NLM", "url": "https://www.youtube.com/embed/lKgWBOMWdVU" },
        { "title": "Mechanics Concepts", "url": "https://www.youtube.com/embed/pg2FdPiWeCk" },
        { "title": "Wave Optics/YDSE", "url": "https://www.youtube.com/embed/Wzi1hBDiyVo" }
    ]
    }
];

window.rawFiles = [
    { "title": "PW Old Test Series", "folders": ["IIT-JEE", "COACHINGS", "PW"], "url": "https://drive.google.com/file/d/1Emnjudx3tfSJct8--uQ2z26TZj86H7oJ/preview" },
    { "title": "PW NSEP", "folders": ["IIT-JEE", "COACHINGS", "PW"], "url": "https://drive.google.com/file/d/17FzVNq7ElEJX8ew_Irk4fEv4av-in3m2/preview" },
    { "title": "Physics ARCHIVE - JEE (Main)", "folders": ["IIT-JEE", "COACHINGS", "AAKASH Archives"], "url": "https://drive.google.com/file/d/1tA2TE6nY8pEqxymkj734VSv-dcn7tev1/preview" },
    { "title": "Physics Archive - JEE (Main) Solutions", "folders": ["IIT-JEE", "COACHINGS", "AAKASH Archives"], "url": "https://drive.google.com/file/d/1BUioz6yZGETzjsLuR4XKlKDO40bERoc_/preview" },
    { "title": "Mathematics ARCHIVE - JEE (Main)", "folders": ["IIT-JEE", "COACHINGS", "AAKASH Archives"], "url": "https://drive.google.com/file/d/1fyN6TqNl54WI1XZkFHiG34Q7HqNOPHrB/preview" },
    { "title": "Mathematics Archive - JEE (Main) Solutions", "folders": ["IIT-JEE", "COACHINGS", "AAKASH Archives"], "url": "https://drive.google.com/file/d/1zGri0N_oUEbrm3qWvB0ik_6YUAaHUfjt/preview" },
    { "title": "Chemistry ARCHIVE - JEE (Main)", "folders": ["IIT-JEE", "COACHINGS", "AAKASH Archives"], "url": "https://drive.google.com/file/d/1nsO5H549jvYWkeyYWcEeegSqJeo8QfRA/preview" },
    { "title": "Chemistry Archive - JEE (Main) Solutions", "folders": ["IIT-JEE", "COACHINGS", "AAKASH Archives"], "url": "https://drive.google.com/file/d/19o6UQZCp7FMyQmyg8IXLb2iJjVTk5oU-/preview" },
    { "title": "R S Aggarwal Senior Secondary School", "folders": ["IIT-JEE", "SUBJECTS", "Maths Special"], "url": "https://drive.google.com/file/d/1roqhcr9mEw2tthlhfZ28uBtbAQeDOCJa/preview" },
    { "title": "Black Book Algebra (Vikas Gupta)", "folders": ["IIT-JEE", "SUBJECTS", "Maths Special"], "url": "https://drive.google.com/file/d/14HukOgsh19UCXfpHXVWA1a7yPurM8rRl/preview" },
    { "title": "VK Jaiswal Inorganic Chemistry", "folders": ["IIT-JEE", "SUBJECTS", "Inorganic Chemistry Special Books"], "url": "https://drive.google.com/file/d/14EVwhdkYYjFDfNiSbh3pWNN_wSF5DFUF/preview" },
    { "title": "Inorganic Chemistry V Joshi Cengage", "folders": ["IIT-JEE", "SUBJECTS", "Inorganic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1ViSbCC3isEKL3_0_p_PxPvKTI8F1ql2k/preview" },
    { "title": "SOLUTIONS OF HIMANSHU PANDEY @EngineeringEntrance", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1cj7cIJaixw7mKwWQog8-H4WM-onicEqG/preview" },
    { "title": "Solomon's", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1hii-MGmLGPfE1990P6xQ2l56MbjSah-B/preview" },
    { "title": "Paula Yurkanis Bruice Organic Chemistry(BLUNT LIBRARY)", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1q4o5H1pwVAvNfdC7tG_PYSYPEgD0jz9b/preview" },
    { "title": "organic chemistry Peter Sykes", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1PjWDWfqgEAM1a8UE12AwZspAnUPyusp2/preview" },
    { "title": "Morrison & Boyd - Organic Chemistry", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1D5_Ah31gmm72wlN_y3U3RNr8rHil_jyz/preview" },
    { "title": "Himanshu Pandey Organic", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1e6M1o-aL3_ljsS_-ez4yGOtaYoSczRUo/preview" },
    { "title": "francis a carey Organic Chemistry", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1rKh__FNDRyVxPesr7TYAswazlEK-2LXJ/preview" },
    { "title": "Black Book (Ashish Mishra)", "folders": ["IIT-JEE", "SUBJECTS", "Organic Chemistry Special Books"], "url": "https://drive.google.com/file/d/1WhdfQp2HibUelWv0IPBz6lkeEN0QM3eE/preview" },
    { "title": "Physical Chemistry (P Bahadur)", "folders": ["IIT-JEE", "SUBJECTS", "Physical Chemistry Special Books"], "url": "https://drive.google.com/file/d/1KRwuBmQUI-2sBqtjdAFVcTZmFhEOJY1Q/preview" },
    { "title": "Physical Chemistry - Narendra Avasthi", "folders": ["IIT-JEE", "SUBJECTS", "Physical Chemistry Special Books"], "url": "https://drive.google.com/file/d/1UdvBPQyfuyqNAw3lUnIj4_yxTRF33H8y/preview" },
    { "title": "Narendra Awasti Physical Chemistry @iitandneetguide", "folders": ["IIT-JEE", "SUBJECTS", "Physical Chemistry Special Books"], "url": "https://drive.google.com/file/d/12ZA84qXWPZM6Mh4eBxIoprhNXBgmV42v/preview" },
    { "title": "Olympiad Arvind Tiwari", "folders": ["IIT-JEE", "SUBJECTS", "Physics Specials"], "url": "https://drive.google.com/file/d/1ZPdcFAif6rlZhuU4Ei9_6zt1uTPcmYGy/preview" },
    { "title": "DC Pandey Arihant", "folders": ["IIT-JEE", "SUBJECTS", "Physics Specials"], "url": "https://drive.google.com/file/d/1FHuoAZrC36sUKKAy3PuHZaEeo_fknDbx/preview" },
    { "title": "Physics ARS Class 12", "folders": ["IIT-JEE", "EXTRAS", "Flashcards"], "url": "https://drive.google.com/file/d/17BOjGk1HO_KZdGKgjItlTag18Wens8vS/preview" },
    { "title": "Physics ARS Class 11", "folders": ["IIT-JEE", "EXTRAS", "Flashcards"], "url": "https://drive.google.com/file/d/1eNXeL3ohXrm0XTGgX3kdZ3RT7h2BO08P/preview" },
    { "title": "Chemistry ARS Class 12", "folders": ["IIT-JEE", "EXTRAS", "Flashcards"], "url": "https://drive.google.com/file/d/10j6hRd8tt5za9bDqUBkR0Q9U4NIAp91v/preview" },
    { "title": "Chemistry ARS Class 11", "folders": ["IIT-JEE", "EXTRAS", "Flashcards"], "url": "https://drive.google.com/file/d/1qytl9OdIW30ijDavvvfSaHZdb9_N_npp/preview" },
    { "title": "@iitjeeadvancedmaterial Mathematics flashcards", "folders": ["IIT-JEE", "EXTRAS", "Flashcards"], "url": "https://drive.google.com/file/d/1dsp04rVqxjgFsUnXHTOttmUVPSYgvfXE/preview" },
    { "title": "JEE physics formula booklet", "folders": ["IIT-JEE", "EXTRAS", "Formula BOOKLET"], "url": "https://drive.google.com/file/d/1-DkwbSvzoYBKtXvx0IUMfYyzur9XcoOv/preview" },
    { "title": "JEE maths formula booklet", "folders": ["IIT-JEE", "EXTRAS", "Formula BOOKLET"], "url": "https://drive.google.com/file/d/1BvvhnHsZ_L-vCKBxVXE1V77ZmGf-Zcfx/preview" },
    { "title": "JEE chemistry formula booklet", "folders": ["IIT-JEE", "EXTRAS", "Formula BOOKLET"], "url": "https://drive.google.com/file/d/1Fp3O8J-Oy82ZBLkkl3cHQtryWx_lGjm-/preview" },
    { "title": "PHYSICS CONCEPT MAP CLASS 11 AND 12", "folders": ["IIT-JEE", "EXTRAS", "Concept Maps"], "url": "https://drive.google.com/file/d/15XEURyXYGyUZz8n3BuJ5tYlf2ELzoWhN/preview" },
    { "title": "Maths", "folders": ["IIT-JEE", "EXTRAS", "Concept Maps"], "url": "https://drive.google.com/file/d/1s31K47z09kgoV9i6wRB1EMsrk5L5r9kJ/preview" },
    { "title": "CHEMISTRY CONCEPT MAP", "folders": ["IIT-JEE", "EXTRAS", "Concept Maps"], "url": "https://drive.google.com/file/d/1FCQot9abtW3KHHXPXt1NKper9xmSQ_IJ/preview" },
    { "title": "Physical Chemhack", "folders": ["IIT-JEE", "EXTRAS", "Hack Books"], "url": "https://drive.google.com/file/d/1GLBEHS_DRrWU6g-BBWjCdaUZtoxxvrlo/preview" },
    { "title": "Organic Chemhack", "folders": ["IIT-JEE", "EXTRAS", "Hack Books"], "url": "https://drive.google.com/file/d/1qsfoK7ythXDqGEorVHwRUbksblQcaGK7/preview" },
    { "title": "Inorganic Chemhack", "folders": ["IIT-JEE", "EXTRAS", "Hack Books"], "url": "https://drive.google.com/file/d/1ngAepRgoe4coWeyVrWIPvYXkAs2a5Q37/preview" },
    { "title": "13 circle formula sheets quizrr", "folders": ["IIT-JEE", "MATHANGO", "Maths"], "url": "https://drive.google.com/file/d/1r73gdV_DUtfS2kulxLeL7qu9ncRjL5rZ/preview" },
    { "title": "16 hyperbola formula sheets quizrr", "folders": ["IIT-JEE", "MATHANGO", "Maths"], "url": "https://drive.google.com/file/d/1i-cNgjD9mlyarv41Gj0lcsU64pT16dWb/preview" },
    { "title": "15 ellipse formula sheets quizrr", "folders": ["IIT-JEE", "MATHANGO", "Maths"], "url": "https://drive.google.com/file/d/1h3UxZkXLsInP5twudypkqQMsZsTNosC3/preview" },
    { "title": "14 parabola formula sheets quizrr", "folders": ["IIT-JEE", "MATHANGO", "Maths"], "url": "https://drive.google.com/file/d/1i48fYdaF7TpgukFDWwgp0ZJu0c1TP6k6/preview" },
    { "title": "12 straight line formula sheets quizrr", "folders": ["IIT-JEE", "MATHANGO", "Maths"], "url": "https://drive.google.com/file/d/1iHl_cWsgpJr7GwdsovIecjdDsijZYkji/preview" },
    { "title": "Logical Reasoning - Puzzle Tips", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1wgi1d6vzxMQ7GWJga5d8SnzQ8fNkLnu8/preview" },
    { "title": "Logical Reasoning - Missing Series", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1aKGSl4SJlqRm5d4QVgKwi2iCudkV271p/preview" },
    { "title": "Logical Reasoning - Missing Numbers", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1OE2ErJQXrTVP7-dDs4Ls-QZogfYYyaxu/preview" },
    { "title": "Logical Reasoning - Number Series", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/16_cZcK3nis00QLMfF9tstcys0znxFH9U/preview" },
    { "title": "Logical Reasoning - Cutting with Symmetry", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1wB6h8vc3FDhS94WK5STMlp9SsGYH8Gyu/preview" },
    { "title": "Logical Reasoning - Cubes and Dice", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1OMTdFoPse8k3svIEDdaA7Dn8PTpTOEPN/preview" },
    { "title": "Logical Reasoning - Coding Decoding", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1-KNGf7HUcDUUcT9Ic5JKYAe1h7E2rtlu/preview" },
    { "title": "Logical Reasoning - Blood Relation", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1y19geHS9qWf4xQziiYfAgSWxjGroRdnM/preview" },
    { "title": "Logical Reasoning - Calendar", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1rreEFkgEuezZ1VnkpWJnHjoeUmQ3BJCW/preview" },
    { "title": "Logical Reasoning - Analyzing Patterns", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1GHy-z_f8WRD9X1AXZKXlBFl-KBk3BAQj/preview" },
    { "title": "English Notes - Grammar", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1ROqAElna1YuGmAvlg_1mpZfPkgFVy0cl/preview" },
    { "title": "Logical Reasoning - Alphabet Series", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1ho8JV-6zcEwBzFXLwPd2hZjwdJhzdxGn/preview" },
    { "title": "English Notes - Synonyms Antonyms", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1U5lTTGi55sI5a5RGD45vWP7wnKPjgovX/preview" },
    { "title": "English Notes - List of Common Synonyms and Antonyms", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1tWNJsH1eIQXk-ty1VKJxhOCO2N5R9Kj6/preview" },
    { "title": "English Notes - Reading Comprehension", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1qOzlR35U16sSm9wJDaoYQ4teRx4rqweb/preview" },
    { "title": "English Notes - Composition", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1XSduR01AOSK4BAw5VCAbYnb6Si9uyeV_/preview" },
    { "title": "English Notes - Analogies", "folders": ["IIT-JEE", "MATHANGO", "Mathongo English & LR Notes"], "url": "https://drive.google.com/file/d/1iI1ZebsVo2bncO_Xrj4miClL6l_yjxqx/preview" },
    { "title": "Arihant NCERT Exemplar Chemistry Class 11", "folders": ["IIT-JEE", "PUBLICATIONS", "Arihant NCERT Exemplar"], "url": "https://drive.google.com/file/d/1iNrIddzztR5L7ThGy8jBl5QKyID0wm-s/preview" },
    { "title": "Arihant NCERT Examplar Physics 12th", "folders": ["IIT-JEE", "PUBLICATIONS", "Arihant NCERT Exemplar"], "url": "https://drive.google.com/file/d/1C_-y17T_C8r2SxFpzTFbrthcUSu8-lxd/preview" },
    { "title": "Arihant NCERT Examplar Physics 11th", "folders": ["IIT-JEE", "PUBLICATIONS", "Arihant NCERT Exemplar"], "url": "https://drive.google.com/file/d/17FKg-WbCUzAAc8TV0WffFc-ok13RGOdC/preview" },
    { "title": "Arihant NCERT Examplar Chemistry 12th", "folders": ["IIT-JEE", "PUBLICATIONS", "Arihant NCERT Exemplar"], "url": "https://drive.google.com/file/d/1hFAygxNOviiMaCvM4yiIHFSrtaTbY3qo/preview" },
    { "title": "Balaji Chapter 1 to 5 Problems in Inorganic Chemistry by V K Jaiswal", "folders": ["IIT-JEE", "PUBLICATIONS", "Balajji"], "url": "https://drive.google.com/file/d/1cVxrUcFMK2aJllzUK8ViDj74dtfGG29x/preview" },
    { "title": "Mechanic 1", "folders": ["IIT-JEE", "PUBLICATIONS", "Balajji"], "url": "https://drive.google.com/file/d/16_E0svoHAIVwOVyGs_eYGLfkwUmA2V7I/preview" },
    { "title": "Mechanic 2", "folders": ["IIT-JEE", "PUBLICATIONS", "Balajji"], "url": "https://drive.google.com/file/d/1UIs_hN81GY2Xit5WmMC1qdQzZkEco3Go/preview" },
    { "title": "Heat and thermodynamics", "folders": ["IIT-JEE", "PUBLICATIONS", "Balajji"], "url": "https://drive.google.com/file/d/1ADZ4qWz6ePnRDgdbnzkZCvQaBO62jfSE/preview" },
    { "title": "Electricity and magnetism", "folders": ["IIT-JEE", "PUBLICATIONS", "Balajji"], "url": "https://drive.google.com/file/d/1fLkEHAhL6G2gLNerXptG28du_aw8g3Wz/preview" },
    { "title": "Optics", "folders": ["IIT-JEE", "PUBLICATIONS", "Balajji"], "url": "https://drive.google.com/file/d/1Gqwmwzbzx-YFmFLOl9L4yYkmY3092oj3/preview" },
    { "title": "OP Tandon Physical Chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "OP Tandon Chemistry"], "url": "https://drive.google.com/file/d/1BjVJ3cgl-zJ2g7sRZX_yjwD8F_haDfeO/preview" },
    { "title": "OP Tandon Organic Chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "OP Tandon Chemistry"], "url": "https://drive.google.com/file/d/15E5y97s7eVP58qOeWrZ5lxP2GZm5fZB7/preview" },
    { "title": "OP Tandon Inorganic Chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "OP Tandon Chemistry"], "url": "https://drive.google.com/file/d/1XZanxWEG2TsT_POpaTbXuOPixM2s5MgQ/preview" },
    { "title": "SL ARORA VOL1", "folders": ["IIT-JEE", "PUBLICATIONS", "SL Arora"], "url": "https://drive.google.com/file/d/1v4JvrzVXLQtgw6WtF7fFxLB08mrgB_uK/preview" },
    { "title": "SL Arora physics class 11 vol 2", "folders": ["IIT-JEE", "PUBLICATIONS", "SL Arora"], "url": "https://drive.google.com/file/d/1jn25_vru7vVN8sgyLmgcIZ7a7vTgneNf/preview" },
    { "title": "Sl arora class 11 vol 1", "folders": ["IIT-JEE", "PUBLICATIONS", "SL Arora"], "url": "https://drive.google.com/file/d/1Jr1rg9CcY5oZs2oJcwuuRb305NIs1zGp/preview" },
    { "title": "Physical Chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "PEARSON"], "url": "https://drive.google.com/file/d/17FnHP3oDcSRJLMB_H2Q0uOT8HRYxgHxv/preview" },
    { "title": "Organic Chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "PEARSON"], "url": "https://drive.google.com/file/d/1Cubh3dtmY0pfn_CCKiviLpHVLCkNkYWP/preview" },
    { "title": "Mechanics 2", "folders": ["IIT-JEE", "PUBLICATIONS", "PEARSON"], "url": "https://drive.google.com/file/d/1tyZDM0UdWPUtIvS5gS6PKuNV6A5RxMXp/preview" },
    { "title": "Mechanics 1", "folders": ["IIT-JEE", "PUBLICATIONS", "PEARSON"], "url": "https://drive.google.com/file/d/1gqP-xjVwGICiS8jnYqfEd6Ipi2Z-iwcn/preview" },
    { "title": "Inorganic Chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "PEARSON"], "url": "https://drive.google.com/file/d/1vf0Adva2_Feqhs0rR7M6xBxHe_gjLlMK/preview" },
    { "title": "Algebra 2", "folders": ["IIT-JEE", "PUBLICATIONS", "PEARSON"], "url": "https://drive.google.com/file/d/1FRAz5Dul21yUreQKo1hyFln1hah9fETU/preview" },
    { "title": "Algebra 1", "folders": ["IIT-JEE", "PUBLICATIONS", "PEARSON"], "url": "https://drive.google.com/file/d/1ujiYp-EotfHKQ02MQa_jXQjfeq6ssZX-/preview" },
    { "title": "Inorganic Chem atkins", "folders": ["IIT-JEE", "PUBLICATIONS", "Peter Atkins"], "url": "https://drive.google.com/file/d/19b8owDcaoGdLtw8KdTojTvOj7fQfsAf7/preview" },
    { "title": "Atkins’ Physical Chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "Peter Atkins"], "url": "https://drive.google.com/file/d/19hXU7_-5tREW2DZXby1i_P_NmJpoDoc4/preview" },
    { "title": "Atkins Physical chemistry", "folders": ["IIT-JEE", "PUBLICATIONS", "Peter Atkins"], "url": "https://drive.google.com/file/d/14nIpxww7-Kja4lko8javBmg5qF6QBCBn/preview" },
    { "title": "Disha Physics 500 BlockBuster Problems for JEE Advanced", "folders": ["IIT-JEE", "PUBLICATIONS", "Disha"], "url": "https://drive.google.com/file/d/13bL7HPqEXVKYu8MoHFibyqIs_acSbtUn/preview" },
    { "title": "Disha Mathematics 500 BlockBuster Problems for JEE Advanced", "folders": ["IIT-JEE", "PUBLICATIONS", "Disha"], "url": "https://drive.google.com/file/d/1r6wsZ8B3W4RAh77vYzyaCDPk3w0Gz5PK/preview" },
    { "title": "Disha Chemistry 500 BlockBuster Problems for JEE Advanced", "folders": ["IIT-JEE", "PUBLICATIONS", "Disha"], "url": "https://drive.google.com/file/d/1ayE4jrU-VMELw7wxIfVwTKGutS2cYcbD/preview" },
    { "title": "Wiley maths class 12", "folders": ["IIT-JEE", "PUBLICATIONS", "Wiley"], "url": "https://drive.google.com/file/d/1bGyEToUBtStKgrvd0VbRYFllmf84mpDG/preview" },
    { "title": "Wiley Maths 2", "folders": ["IIT-JEE", "PUBLICATIONS", "Wiley"], "url": "https://drive.google.com/file/d/190nwPG0oqYCgZciDGxKWw3EAvpaWFTqx/preview" },
    { "title": "Wiley Maths 11", "folders": ["IIT-JEE", "PUBLICATIONS", "Wiley"], "url": "https://drive.google.com/file/d/1M9e1BnvzslFPe7BTn7YLWI4R6Z-AP7We/preview" },
    { "title": "Wiley Maths 1", "folders": ["IIT-JEE", "PUBLICATIONS", "Wiley"], "url": "https://drive.google.com/file/d/1T_CqRlFIEF-1phkyVQi25wsXzEXZIKQe/preview" },
    { "title": "Wiley Geometry", "folders": ["IIT-JEE", "PUBLICATIONS", "Wiley"], "url": "https://drive.google.com/file/d/10CHORKTj0VKfslxMNn-LwX1EucsKLsZI/preview" },
    { "title": "Wiley Algebra", "folders": ["IIT-JEE", "PUBLICATIONS", "Wiley"], "url": "https://drive.google.com/file/d/1f8_Ad-cueHWAaKGN0pRTgp5LlVmKq7xZ/preview" },
    { "title": "Calculas", "folders": ["IIT-JEE", "PUBLICATIONS", "Wiley"], "url": "https://drive.google.com/file/d/17AIeddxg7BHxVKnY1dwn6FSyrtLmoPVN/preview" },
    { "title": "PhysicalEducation12 2022", "folders": ["IIT-JEE", "NCERT", "Physical Education"], "url": "https://drive.google.com/file/d/1ab76PqmovuHj1_BcIh81L7zYqWcQIDQe/preview" },
    { "title": "leph206", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/15zJ4nmakh1oiVsbBOAqxBJo5Gc7dl97Q/preview" },
    { "title": "leph205", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1hqV2BZl1_X6HcadQoz-fT5RJWPEcxsbF/preview" },
    { "title": "leph204", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1Br5FOhX71xO5wOqRAMsx_85g9Fa0xKe7/preview" },
    { "title": "leph203", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/153v6X_XboAx2YHh2_9J8nCUzutEfzYgX/preview" },
    { "title": "leph202", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1hPuacGILKRefl0lj1hwp8FPt7X_HL5Bb/preview" },
    { "title": "leph201", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1l1jMCBlre3j7c9u3Qn2x3PTghJS2QlsA/preview" },
    { "title": "leph108", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1K8NrfRZ-Y67NB-zQx6MUgOwrQE-U6AtW/preview" },
    { "title": "leph107", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1m3KP0bs3QMK75H8FJ5EYNoiDpUmrueDK/preview" },
    { "title": "leph106", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/176bMRG-1D2XOT9fBtNYX45eRVqZH-6WP/preview" },
    { "title": "leph105", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/121awrY83XfnbSlPPqypGudJfoBBJyNCs/preview" },
    { "title": "leph104", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1VeWQQIG0VZJ7cpXguplJj9JyUF7rrNxF/preview" },
    { "title": "leph103", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/16-3OGqy8bndGAKQ37g0dj0sKw8g_0Z2M/preview" },
    { "title": "leph102", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1P0oPdl46DdAw55eJBGuwwi10Xr-j1gaQ/preview" },
    { "title": "leph101", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1j-X7p6B7DlIoAHgH_h1auQef6J0pmUn1/preview" },
    { "title": "Jee Main Physics Syllabus", "folders": ["IIT-JEE", "NCERT", "Physics"], "url": "https://drive.google.com/file/d/1Icw61aNVJ_1MKfumgYQHwShdrFmdsudM/preview" },
    { "title": "levt1ps", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1FBJBUOUmN-yBOBuuM7OBvvZwkP3uRmks/preview" },
    { "title": "levt105", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1pyHmhwdLWy9zWUyvlKTTABUe5P-E-E6M/preview" },
    { "title": "levt104", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1cUGkTZTmT4NED-OwYv4ohJcA69mMaCYT/preview" },
    { "title": "levt102", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1yS5w8i6Ah8xSjloKnAnTDy_Oz9cYH9fG/preview" },
    { "title": "lefl1ps", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1YUmdTTdOrCwOLjfF2EXVLeMCX0QybcmW/preview" },
    { "title": "lefl101", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1b2ntFDXGf6zNMZucSIge9tC5obe65oOb/preview" },
    { "title": "lefl104", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1m_g7_yTtpTuBn875kbWsFWj2yvqQ_mzB/preview" },
    { "title": "lefl102", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1aZW-VTi2ZOzaOqPRB5h9pUXzgvxhLZCN/preview" },
    { "title": "lefl108", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1Pf3Tdyp0KHQGgzmXdUCB43QJtu9rAq_7/preview" },
    { "title": "lefl105", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1N79zI75SIeiM-QyMTDMVLzOHQ7UNLcGt/preview" },
    { "title": "levt106", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1Xa4f08lzFKa6_p1MDcQFW6Ax5y1iefl6/preview" },
    { "title": "levt101", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1HUM_WNPB-8xfXCD12X7zKN5o33rbJJ3c/preview" },
    { "title": "lefl103", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1iZr-9UBP_Xm239L9ifGWVgy2MVneP6ja/preview" },
    { "title": "lefl106", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1V8In8xITTIj1ULpi6nj4OvotgUHwb8tL/preview" },
    { "title": "lefl107", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1R4YpXNnHi1fdHxWvfqQa1IgavU6HHghj/preview" },
    { "title": "levt103", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1M3z5PSNVLTkOgrardctAwLjyT19DGftI/preview" },
    { "title": "lefl115", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1zflPUIEdv4ege-OvwRTCYFu7dpr0xcht/preview" },
    { "title": "lefl111", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1ka1JWaYbUuF9cPwUXemFpc2yDPqoEoGu/preview" },
    { "title": "lefl114", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1J0eYZa60Fd-Jgl3B_5ZYy3u9MuVN-FGY/preview" },
    { "title": "lefl113", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1A4Ptoy-bajV2RhjrKtqc4tvEViskVDmC/preview" },
    { "title": "lefl112", "folders": ["IIT-JEE", "NCERT", "English"], "url": "https://drive.google.com/file/d/1LMdRpyW8DeE6KpNA3fUAl8VLYuqopPfF/preview" },
    { "title": "lech205", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/18vKrFaRicotPCj7NN4BqOQZuOko9OBYx/preview" },
    { "title": "lech204", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1v7sqHRUdVivyTgEIFwI91krpufwF7IX6/preview" },
    { "title": "lech203", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1dTvdqgFN3nkKkvWosgmTcPDu4m08kmRP/preview" },
    { "title": "lech202", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1smH_l4qUHyXbRtLQW5dwAQdUnjBywvPt/preview" },
    { "title": "lech201", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1GsKv2-M3gAmhS8Iumc9VTC16tG-xrwfP/preview" },
    { "title": "lech105", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1kBmgy--Mmo2rveZ0SUFHp7LjT9c3YGoD/preview" },
    { "title": "lech104", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/113CKLW8AlDDFRFlUDnJNLJYk6VqNI0H_/preview" },
    { "title": "lech103", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1qvA5UChSUsgOfCf29E-oc7RCW1on45Ke/preview" },
    { "title": "lech102", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1C52qs9JSBmYR28R7VyGPR-kFluoAhMb5/preview" },
    { "title": "lech101", "folders": ["IIT-JEE", "NCERT", "Chemistry"], "url": "https://drive.google.com/file/d/1Cf_qeBqmZJFcIRh7EDsMNyOjI1sNQ6gN/preview" },
    { "title": "JEE 47 Years JEE Advanced Physics", "folders": ["IIT-JEE", "COACHINGS", "PW", "47 Year JEE"], "url": "https://drive.google.com/file/d/1Nyv7aLN-adqKzgy2hDsBBaeKL3c1qjX5/preview" },
    { "title": "JEE 47 Years JEE Advanced Physics (2)", "folders": ["IIT-JEE", "COACHINGS", "PW", "47 Year JEE"], "url": "https://drive.google.com/file/d/1yZ0ftszCR5v1kdFtZrGBkWJVzgHlsaUj/preview" },
    { "title": "JEE 47 Years JEE Advanced Mathematics", "folders": ["IIT-JEE", "COACHINGS", "PW", "47 Year JEE"], "url": "https://drive.google.com/file/d/1tTwjo7ypQPXOdDz40NZBhoboBz2V-kvP/preview" },
    { "title": "JEE 47 Years JEE Advanced Mathematics (2)", "folders": ["IIT-JEE", "COACHINGS", "PW", "47 Year JEE"], "url": "https://drive.google.com/file/d/1MQXIlmT0jAKsKUjuneoP8Kni5R4Z-s3c/preview" },
    { "title": "JEE 47 Years JEE Advanced Chemistry", "folders": ["IIT-JEE", "COACHINGS", "PW", "47 Year JEE"], "url": "https://drive.google.com/file/d/1o4tatzPu-6nu81RTSmuGPP88nhcThUGA/preview" },
    { "title": "JEE 47 Years JEE Advanced Chemistry (2)", "folders": ["IIT-JEE", "COACHINGS", "PW", "47 Year JEE"], "url": "https://drive.google.com/file/d/1YmMXSuSpO4fHnHpI4_4a__IMLMUlTAyw/preview" },
    { "title": "WEP", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1xULnniKoj59JwLEi8AXJv4n51UiACQiS/preview" },
    { "title": "wave optics", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1AgKut73Qr_Du05cELF2hGcl8x8NORcjD/preview" },
    { "title": "WAVE MOTION", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1eG_N2BL6hjIC3OynNeZi5ZcotCPm3uJ_/preview" },
    { "title": "Ray Optics", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1ZT2CcRbV4mEbkN1bPxKFgU1l9RrD5nMK/preview" },
    { "title": "SHM", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/11o5EqW3f92OecPIfc0E1tF4G83uFcCHE/preview" },
    { "title": "thermal physics", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1T-W2u2GcdqdQh6PSb25QEMTv-daahqIb/preview" },
    { "title": "semiconductor", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1p_sPdnFMSbiskCEW173UfbPUv1kTporN/preview" },
    { "title": "Physics Module 4 solution", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1A3I8A7r3ckWxEw075RWTa0qyb0mK30nM/preview" },
    { "title": "rotational motion", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/136jvz4DUPwgFqVVoUbCL5yUVKoDMG_tS/preview" },
    { "title": "Physics Module 2 Solution", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/198VWd_BR43sRxYq27am8gVdeDHbepYHj/preview" },
    { "title": "Physics Module 1 Solution", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1q0fUx3x2k6xNS-6XHmHYWorrG3eT-jsZ/preview" },
    { "title": "Physics Module 5 Solution", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1Ff63q0W-8a5lgMDdaEX5FmYmV1gESgig/preview" },
    { "title": "NLM", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/12rGR_t0rbAalfcvS1liHgCg6ZzFtMads/preview" },
    { "title": "modern physics 2", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1etQgEfaN6scWlBWbQZUVEbs4MEyZ5Mm1/preview" },
    { "title": "modern physics 3", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1w_FE2VeGKv6QJJzvFlaZAvjdQvA8kOVp/preview" },
    { "title": "Magnetism Module", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1Pr7AiY_flRQmZaOSaWWzsowJjF1fxENM/preview" },
    { "title": "Physical World Unit Dimensions Error", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1h-yY0G0jYXm5hzF0ZEgEqL_WfOyHzrXv/preview" },
    { "title": "modern physics 1", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1r9t3BAWQukY9-5hWNXh-qr2uQP1jF1sU/preview" },
    { "title": "kinematics", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1bvIu_ADongu9euU_IG8gmI7gJRlbwTQL/preview" },
    { "title": "EMI", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1OaJElTRy0gWn3dy9UZWsH-ima3ILqEwE/preview" },
    { "title": "gravitation", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1JT3wytjJjJBZGd7EV7emA563Csu0GDXz/preview" },
    { "title": "electrostatics", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/17-pl-QrrvuyCpF2QvbNfjdEV32sTYub1/preview" },
    { "title": "current electricity", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1nxzaSZaLEzj22bJ3bgJqPONYEbf2_EmF/preview" },
    { "title": "com collision", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1HbRjHRtmO5NmvOwYlqjbFwUbexvxa6AO/preview" },
    { "title": "Circular motion", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1I7p3siljsC5rOZA7yeNK7Q1cNbbqszqE/preview" },
    { "title": "capacitor", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1S4CT-NdklfwBsOPdfSCfYJmOczVA6U0Z/preview" },
    { "title": "basic math", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1odngS2g1Owh-K0JqTyI1Z_GayO8dBRCq/preview" },
    { "title": "Alternating current", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1kT2AWWti5Gg2_AwZz5KvLJCCBqKwUTye/preview" },
    { "title": "ALLEN PHYSICS RACE SOLUTIONS-2021", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/178xaPf58qPmEyPLq401YQX2muFGklp9G/preview" },
    { "title": "ALLEN PHYSICS RACE 2021", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1G_Ol5DxwFLjcBgAsxU9AavQf74_wRRcm/preview" },
    { "title": "Physics Module 6 Solution", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1EgwquKwScWV7UskP7SWkPTOM5z35ynHz/preview" },
    { "title": "Physics Module 03 Solution", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/19TI7oxTCgwqEjctBywBLCVPcBYPzVwOp/preview" },
    { "title": "EM WAVES", "folders": ["IIT-JEE", "COACHINGS", "ALLEN", "Allen Physics Module"], "url": "https://drive.google.com/file/d/1SsTDpQ5XAPvW6UkFlN6UDgw2c1zO7Qte/preview" },
    { "title": "THERMODYNAMICS 02", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/18_mcOetIuv2-XSXBaLbIO_G-FwrymI1A/preview" },
    { "title": "THERMODYNAMICS 01 SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1jRh0FyjWCHHuCaXIhdEv7Tj8-AZiXUD6/preview" },
    { "title": "THERMODYNAMICS 01", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/12UUAzXguNgETp-BguebpE55Q72HDlQhs/preview" },
    { "title": "THERMOCHEMISTRY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1a1E6DuNdllWzIm5rUuBfBWNxUBijn6f0/preview" },
    { "title": "REDOX REACTIONS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1-J6BPBQmUszCdnnkH0wyAheCuGQrUhEn/preview" },
    { "title": "SOLID STATE", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1kwHYdYSP-bO2NAtmQKA9f4HfljUNhyRG/preview" },
    { "title": "SURFACE CHEMISTRY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1FpB8JGRMPd60TAGygocRTFLkqDow-Hb_/preview" },
    { "title": "REAL GAS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1GDXP2sJlQ4do05hHh_IoAbRTk22aeMlu/preview" },
    { "title": "MOLE CONCEPT", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1n6zANn6Gz32GhLbCo7tEL4wZPHprhi0W/preview" },
    { "title": "RADIOACTIVITY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1gTBwoGU5GzaaOIlG2ZihDSEEmyJH9aFG/preview" },
    { "title": "LIQUID SOLUTION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1H950_SoOzi4Ll_9AYQ7syc1STV4BOBss/preview" },
    { "title": "IONIC EQUIBRILIUM", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1PepL9JEy1d3vNGITz9aquE-wlRr5-vF6/preview" },
    { "title": "IDEAL GAS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1TIQrbMh-L6oplN2LR3iQanv5jgWwrB0c/preview" },
    { "title": "ELECTROCHEMISTRY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1138LQl_OegEByQ-hYgY3DnIVEd-zOhhf/preview" },
    { "title": "CONCENTRATION TERMS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1JyGSHZnq3DSPFDFXvB3N0rVm515BjTu9/preview" },
    { "title": "CHEMICAL EQUIBRILIUM", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/19bkGlS526PHEdS4lPbOkO7--aUMJvf1_/preview" },
    { "title": "CHEMICAL KINETICS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1s3dIxGCC88WYOAV5XlD7y2cNxGNx1vt7/preview" },
    { "title": "CHEMICAL KINETICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1wI9ioYcRAOZ6ogSR7eW_zu4RalzUmnDX/preview" },
    { "title": "ATOMIC STRUCTURE", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1SaqUlWE20CDg3AgUyaVn-0cu2rsYWd9n/preview" },
    { "title": "SOLID STATE SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1_uE3Uf1lBvL6hP1epYlk2fMgCZzR_c58/preview" },
    { "title": "MOLE CONCEPT SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/11hDexOsXH5WPjqVqsw_PprJ2P3XALwcJ/preview" },
    { "title": "RADIOACTIVITY SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1a_z_rVmIMEprK3vJurvEVOkql--MbG3k/preview" },
    { "title": "CONCENTRATION TERMS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physical Chem all material combined"], "url": "https://drive.google.com/file/d/1UmNWQ1bP23QFAOedy80zM23v3Wi9ye8m/preview" },
    { "title": "SUBSTITUTION ELIMINATION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1GwGaSv32UZK70oRhjqdvxjHj6KRJBc5K/preview" },
    { "title": "POLYMERS POC", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1SWqX_mHSdU_v6x84yvQ5JjI-p8z2NKzE/preview" },
    { "title": "REDUCTION OXIDATION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1ElfKw0ghE3CHRiCy__mQj-w3tuydYurK/preview" },
    { "title": "IUPAC NOMENCLATURE", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1cc3ts2K23zknehhfkTRERPrqH25Q-LOS/preview" },
    { "title": "HYDROCARBON", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1tYbnp3etrxdoxFMbZPNWbaxAgkjfqpP7/preview" },
    { "title": "ELECTRONIC DISPLACEMENT EFFECT GOC", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1xq_dheRxFUmkKWYohEMFkv7sOMIWe-lH/preview" },
    { "title": "CARBOXYLIC ACIDS AMINES", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/19uRStPW01R1GZHeePW7Q8B84pCjrfZN0/preview" },
    { "title": "CARBONYL COMPOUND", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1psdLjJSST4j9sMmDKMN_0LGH0kZyVair/preview" },
    { "title": "CARBOCATION FREE RADICAL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/18QRTYT4SHbEYl4Oz9l_7FlkAvE4Mnpnm/preview" },
    { "title": "BIOMOLECULES", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1EQZEUIyDMO0O7MmCpmwY368D_vzck3lQ/preview" },
    { "title": "AROMATIC COMPOUNDS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1nFl2KwQtYcZye-htOP61o5IoWSV8t5zB/preview" },
    { "title": "ALDOL SIMILAR NAME REACTION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1KV72VMfo7v_kybZNRxhbX2b4hi1LOBfB/preview" },
    { "title": "ALCOHOL ETHER", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1dXi_4gGMGaJQj9eFqMOLjcmXgVrJWnXw/preview" },
    { "title": "ACID BASES", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1_2WczhgMG3HR1M-RQgbdw4SVpkSFDoj9/preview" },
    { "title": "ISOMERISM", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1xP7q9XX1b798bbirClT6K59kWEYXDSAF/preview" },
    { "title": "STEREO ISOMERISM", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Organic Chem all material combined"], "url": "https://drive.google.com/file/d/1jmcg7ApU5gx17TJadMJ7hXn3HAPhKYCO/preview" },
    { "title": "VECTOR 3D SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1CNPCPWYJFZmME5_aN_4dxPUHsNif9-bI/preview" },
    { "title": "VECTOR 3D WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/10lw0pFZHr_3vtfNBaFmPRW8LQ7grsNpV/preview" },
    { "title": "ST LINE SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1qfLLl2FXFwpNEO1K2asg5G11ueBEwf9v/preview" },
    { "title": "VECTOR 3D SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1UKddBCT476D0AVANXW4QBQe9A1F_U4-_/preview" },
    { "title": "TRIGONOMETRIC EQUATION WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1VKKZmra9YgI-cH4akRlJZ0g4QbEolJs3/preview" },
    { "title": "SPECIAL DPP INTEGRATION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/17qsbbM3e3vG7CnPLA5ZUPvJ_jt4qfASU/preview" },
    { "title": "TE SOT SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/11DVOJ55Z-ywaTwBLGzG7hnO3UTz3NINF/preview" },
    { "title": "ST LINE SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1hhQhO_-dC25bWc9Nx-RfS_Kx1O9HcrWi/preview" },
    { "title": "TRIGONMETRIC EQUATION SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/10IJPXMAJuZGSn0PsMa2PEr6q_GTWaDiE/preview" },
    { "title": "STRAIGHT LINE WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1_UWYQoSQIw7wp4WRwfpvv7X6_HmQdxpb/preview" },
    { "title": "SEQUENCE SERIES WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1SJEsXZiG85er4dYw-JWo-tHIEvzcC7oe/preview" },
    { "title": "SOT SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1MDbvgRHjU1GA3BBdB-s5enLPeULzP3AY/preview" },
    { "title": "SOLUTION OF TRIANGLES WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1DHgQK71psHN_gAYBzZeIdGkVswiXrgmx/preview" },
    { "title": "S L LONEY COMPOUND ANGLE SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1a2oHImqGqD6n3sxi4gCXNHEH65m_KGAu/preview" },
    { "title": "SEQUENCE SERIES SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1tO1br4bqL7S7h5ljW7qpWGwQSy4LH5jO/preview" },
    { "title": "QUADRATIC EQUATION SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1YvsS0ny5mE5o-Ao0AO1OTRUwyKiX3WvK/preview" },
    { "title": "QUADRATIC EQUATION WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1ztCkESFdIJSq1-POoQ8WCasRUxB-7PbQ/preview" },
    { "title": "QUADRATIC LOG SEQUENCE INEQUALITY SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1VflIal16FNAugn-9RcnL6LgLwi0PHXfH/preview" },
    { "title": "PROBABLITY WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1scBgpsLfQQk-K0nUONPxgvKLGDcbC--q/preview" },
    { "title": "PROBABLITY SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1wOkiGDiSrF2STy4EYfq__ycaYMTAZDhp/preview" },
    { "title": "PnC SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1boSyKBvSJEeF5o33HmbFIv3NuJPnVvPa/preview" },
    { "title": "P and C SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1NVNYgCQZSDJDxqAqelK8DI9Smo1tIHBI/preview" },
    { "title": "PROBABLITY SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1VhwvQo0YscE0pUyum_zShn2px_DjguTH/preview" },
    { "title": "PERMUTATION COMBINATION WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1CWsMzd5R0kYXxE3eVNNJbvQRTXushlqR/preview" },
    { "title": "MATRIX SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1FIfpgrpA0rxunh1t0KVNFqqGRszGYpk7/preview" },
    { "title": "MOD WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1Dg1-C8NiS6A2SI2Ph6iNMag91HtvVM8k/preview" },
    { "title": "LOGARITHM SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1v5ErYP35CuKB_JaT1AmY60JW3j8PZ_1S/preview" },
    { "title": "MOD SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1iZhCBlXqJG3fGvPVCCpO3AAW3k4DhfKQ/preview" },
    { "title": "LOGARITHM WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1YteatMgN4_wGqX7IPYzQejhBBrx_BX_D/preview" },
    { "title": "JEE MAINS TOPIC SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1y1-WJw3hRZJZo8PNRij9c3hXc4cFYgxt/preview" },
    { "title": "JEE MAINS TOPIC WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1ISoLBLdO-_vPXrNWJk_mpy2kAxZaPMsS/preview" },
    { "title": "LCD SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1I7oj7cK2gN9k5yQRw-B9kNT_7P_E7CTB/preview" },
    { "title": "LCD WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1i6ZfCILubZHLKviMFyD4TgruUrL0vRfH/preview" },
    { "title": "LCD MOD SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1iTVQG2xKgKoG2NpS6wIKW9F_nxxQgUQP/preview" },
    { "title": "ITF WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1c5PDH-45yCjbK_blRBBQJgl65Nu0OsZp/preview" },
    { "title": "INTEGRATION SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/14idOSLu4txozg19w3WlnpKKEJVwvLcFJ/preview" },
    { "title": "INTEGRATION WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1OOtK2RubRIX1lj7xm8ad1c0VNpHb4PDT/preview" },
    { "title": "INTEGRATION SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/15HzkGah9lroiB-kYf1ErU7Y9slFz3mAj/preview" },
    { "title": "DE AUC SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1Oj63WYRRqhfgHe1gEf6wzcEJwKsrxDTl/preview" },
    { "title": "INEQUALITY SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1tbn_hP5PHqgoSzcGDHoSUyZx3DLZgD8v/preview" },
    { "title": "INEQUALITY WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1TaptuIBpPsH10FaN4Vi7cdYaNaU8VuMH/preview" },
    { "title": "FUNCTION WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1j7xoda99qLZVfjs8C2H5ZY7GnFa9BQuI/preview" },
    { "title": "HALL AND KNIGHT", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/15clOLKkw0R9GD5Dolw5THxTQAlDOh6zN/preview" },
    { "title": "DIFFERENTIAL EQN AUC SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1VaYXXcgJe71WC5FvyKRZ_7Q7DGJKn1j7/preview" },
    { "title": "DIFFERENTIAL EQN AUC WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1A5kDlX5Se04liMvMLJT7k-7I1AXyY49h/preview" },
    { "title": "FUNCTION ITF SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1P2F67KaR457gkxbw2rO8Mbc382vDf_Bp/preview" },
    { "title": "DETERMINANT MATRIX SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1Q91kSwk1OjYHlzimYbCoYajkBbfqOxsD/preview" },
    { "title": "DETERMINANT WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1tnt62RGpLWMp4NDadG89SQMZtXYBnNTR/preview" },
    { "title": "CONIC SECTION SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/18rwizlvVcVTQcZt1hpzpqNJ4hkdJlIZN/preview" },
    { "title": "CONIC SECTION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1HOdy4jWiOwzUeOjr-WrJC8xPwk999opg/preview" },
    { "title": "COMPOUND ANGLE WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1kjeASY3wZH8xLXVJNb2fAv2KL0sInZhO/preview" },
    { "title": "DETERMINANT SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1wJdNSSH4GrbD6UGceYkkyDnyXwNFjvES/preview" },
    { "title": "CIRCLE SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/16d6tLa7GiVrzPDEg-UQOd6lHpqiM0utQ/preview" },
    { "title": "COMPLEX NUMBER WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1KN9HRv-s5dtMLNdMxOQjyEwlqDGVnNgA/preview" },
    { "title": "COMPLEX NUMBER SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/11NoDhy536AUkVkpMTa_KdJAwCildNq0B/preview" },
    { "title": "COMPLEX NUMBER SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1iKeU-MkPT-omXLhMssZvV0CW4fZLe3tV/preview" },
    { "title": "CIRCLE WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1MRZ0ofaNjuSoZ8l2srYKLfD0-dS-_b9d/preview" },
    { "title": "CIRCLE SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1jUT6sbOxuls-NUov_HUiz_eJ9Ezw7vPm/preview" },
    { "title": "BINOMIAL SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1rJXkS8Zqi8C7EHMJGqrI7Bskx7_qGmDX/preview" },
    { "title": "BINOMIAL THEOREM SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/109A9iOpB1QsE_HeKkk0Sg2qDXrgNz9XI/preview" },
    { "title": "BASIC MATHS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1tV7H_biFJ3x43oXNvIXhh2XP2zdCMcHu/preview" },
    { "title": "AOD WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1ETxnDKQ_ymbuiOKdG1rKErk6wfdd3MBE/preview" },
    { "title": "AOD SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1jUO4SqGIfS8J2xTcWGVAeZMUe-BSAwml/preview" },
    { "title": "AOD SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1_d4b2kyKaZPoE9wfmaIw5xyVIVOJsZQk/preview" },
    { "title": "SPECIAL DPP MOD", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1y_rV_RQUnmeiLBTITGd3Q4NU8_lV6iQp/preview" },
    { "title": "MATRIX WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1KaEwpsBNo75S7wrBVTa_-ah8TEJ-2JpH/preview" },
    { "title": "FUNCTION SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/190V4cRwPhMAAhgY-yzGZjzb3tIjJbI1K/preview" },
    { "title": "ITF SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1igyT9TtO528hFipLHOwxkT1iyhd8sul5/preview" },
    { "title": "COMPOUND ANGLE SHEET", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1Gqhqpm4gh0BRyz7ESUGMWqGmTCih2yai/preview" },
    { "title": "BASIC MATHEMATICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1lsj7nbH4tDTS8GC1zZSodqVXNyo5pwBK/preview" },
    { "title": "BINOMIAL THEOREM WORKBOOK", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Maths all material combined"], "url": "https://drive.google.com/file/d/1bseMjg43y2CNlAMw8zFLokQRVmghnndm/preview" },
    { "title": "SaltAnalysisDpp00to19", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1Sln4QD-RWLmRtk5slk9jGA-hBHyRSGfs/preview" },
    { "title": "PERIODIC TABLE AND PROPEETIES", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1LfhOnXEACveq6Rh6ebVk099Z6GjLBQlC/preview" },
    { "title": "SALTANALYSISDPPSOL.01TO19 (1)", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1jyW0WNXF_gPl2YH562yFtMzsNJRzPTjH/preview" },
    { "title": "SALT ANALYSIS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1kE2FRbIFKVHI20CSQAFxN3CH65aj8thX/preview" },
    { "title": "S BLOCK ELEMENTS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/17Dw0f6mNb_irJ-zJE8ryW7FxX4SQxiY_/preview" },
    { "title": "METTALURGY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1cEfbHxGPoJRgyOaM7f71DZ7wmyKWKa_w/preview" },
    { "title": "P BLOCK ELEMENTS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/13Js67CwPIGwsKYhcrl_4i4lc2EZjjIh1/preview" },
    { "title": "IMPORTANT QUESTION IOC", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1QwqMq0_Fw5KKWfZj9hkKCGetEabROoHp/preview" },
    { "title": "HYDROGEN", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/10GTGvz16Vj6OggzVvPU0f6WNdwMBd8jm/preview" },
    { "title": "ENVIRONMENTAL CHEMISTRY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1WhijOo4YA9X8jZeIFHPDyytZj3s60tWT/preview" },
    { "title": "DPP-COORDINATION1to11 (2)", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1EKqOAWw4xX1xbm5770-3qUjGRdr4-cvz/preview" },
    { "title": "D BLOCK ELEMENTS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/15whfiz3vlrEms8ToccIwdZSNi5fl1sAg/preview" },
    { "title": "COORDINATION CHEMISTRY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1fmexKj8CsaHwN9BpxtE4h7hxMt8SWkUj/preview" },
    { "title": "CHEMICAL BONDING 02", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1UBQ43kUY06IOPBChBGhrXc1whWZyDYO1/preview" },
    { "title": "CHEMICAL BONDING 01", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1hKRkm1uJ7l2xn2HavnKcQdenC9eyMpqA/preview" },
    { "title": "MetallurgyDPPanswerkey (2)", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1NyxAHhSbKyEs2ZhaLleQuTdiV1M-Imeo/preview" },
    { "title": "F BLOCK ELEMENTS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/13GIV3GkNSpI98szERL5psLR_oeWLitJ3/preview" },
    { "title": "QUANTUM NUMBER", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Inorganic Chem all material combined"], "url": "https://drive.google.com/file/d/1l-YiNp6cxhwllMiDboNm15o5TAaLTC-y/preview" },
    { "title": "WORK POWER ENERGY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1_bLGNVletLtckmCQc1SWnYkjkfxveQqC/preview" },
    { "title": "WAVES", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/13vHR3kW4_8q8T0VIvNismYaBh54Pegk8/preview" },
    { "title": "WAVES SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1h5UZ4eFklHAIavTyYCjgj8BBeoEVbOmQ/preview" },
    { "title": "UNITS AND DIMENSIONS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1LlGoorVU5XrEzuiL97GZltzDsfWPF4SS/preview" },
    { "title": "RIGID BODY DYNAMICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1s8Kryi_cujPj6nl7i8UhckNqgudrO_7w/preview" },
    { "title": "SHM SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1XrUH2uHB8YZiCal3LnGXPKRaDtIaATGT/preview" },
    { "title": "RBD SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1i_L6LFconFA2Ukdg1RtL6oIRbmxUuN_M/preview" },
    { "title": "OPTICS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1IANGbOHXAZ6UNWIA-bSO6HlDR97VI2NY/preview" },
    { "title": "ONLY JEE MAIN TOPICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1q70URE_INYFUSfvbCxo7YcUnm4rXox42/preview" },
    { "title": "NLM FRICTION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1ekDiD1p_IhAGlZE3aUpsjNwEL1MKJwmD/preview" },
    { "title": "NLM FRICTION SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1biGMCXYYfDJCFpUrcXvEbMz-r9qpJiSy/preview" },
    { "title": "OPTICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1dV7ADNYhc5R70skNAT5wI3G0Sg7NxbIq/preview" },
    { "title": "MODERN PHYSICS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1DxMVlA1tLKxLwlsSRsjCCOm70vq1Xsgp/preview" },
    { "title": "MEC SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1Xkemn634qijAiauiOTlfeOFIsPVRwMQd/preview" },
    { "title": "KTG THERMO SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1bPwqOWhE9RjutbTKQXgILJ8MV2hm76TV/preview" },
    { "title": "MAGNETIC EFFECTS OF CURRENT", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1cocef9OO-FVdp7RReEJV7t6GWI6OsfuQ/preview" },
    { "title": "KTG THERMODYNAMICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1qQ51a69QLC5MNwL7XnSSVHEBpSpc5o8J/preview" },
    { "title": "INTRO TO PHY SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1XWkvzCju3aqP49g7WIsNb5oANKIDlXeg/preview" },
    { "title": "KINEMATICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1hZU18Z6kDSk06S95sSOefE13I51A5IsC/preview" },
    { "title": "KINEMATICS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1wypFbDemNZ7ki2aK4nCTJs0pWtO8xZ0Q/preview" },
    { "title": "EXPERIMENTAL PHYSICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/14CeUayh75I9-6D5fER3JnXMMA7Ofx8TL/preview" },
    { "title": "FLUID MECHANICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1MYAoiERjFDdcEAAu2cfd1pbK4spkjmaI/preview" },
    { "title": "ELASTICITY SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1r77hBwB3hJc3wLISUzUyIQTlexjctdMF/preview" },
    { "title": "ELECTROSTATICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/129501PgA2HQCanJxETeUVgkSuO9sJp66/preview" },
    { "title": "ELECTROSTATICS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1pc5C0mgg23gpPRjDgimezvW8ih2aR4Y7/preview" },
    { "title": "FLUID MECHANICS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/16vAQ7-jwxa06CxSDJhV4xz9-5OzsTbnl/preview" },
    { "title": "EMI SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1NqMkkuU-Xg_e-ZhmG8VBn6BX60qnrTtw/preview" },
    { "title": "ELASTICITY HEAT T CALORIMETRY T. EXPANSION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/19DagY_M1pyNSAcpA36WFXVbuv7xNyeP0/preview" },
    { "title": "ELECTROMAGNETIC INDUCTION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1reoYl5KyoHUsupk5T4dfTF9LbkTIp5dX/preview" },
    { "title": "CURRENT ELECTRICITY SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1Xey717viqw1xlb4kSOELiZKYtSYpg2RF/preview" },
    { "title": "CURRENT ELECTRICITY", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1xE-vjIildJddke88M10ftyp5PP7Txp4X/preview" },
    { "title": "COM SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1fPF1T6pUekrCIDHZBRkwS0WF9K_QaI5P/preview" },
    { "title": "COM MOMENTUM COLLISION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1pqdSL5uDwes58ubcGdj87Y9VYiyHbs-1/preview" },
    { "title": "CAPACITANCE SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/16-VMiFsmsl06pcvoN4a1JmWaSm8SNjyQ/preview" },
    { "title": "CAPACITANCE", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1RBLsMciAtKyP89YRPhGdeS9EXfdy9SWW/preview" },
    { "title": "WORK POWER ENERGY SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1lmnC-Z7b0nOZBIZXQ4k7mDIMyTLa7RDh/preview" },
    { "title": "GRAVITATION SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1EIiR_2xpF5C_z9p3TW9LYVGv0GXLBeFC/preview" },
    { "title": "SIMPLE HARMONIC MOTION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1w2etrCBlfdDPVQFMXGT5bc1n57nVxgRQ/preview" },
    { "title": "UNITS DIMENSIONS SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1co8RkEYE3g5-3CDpChp7HdhC12eSPZXT/preview" },
    { "title": "MODERN PHYSICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1RgQlSmLCIVQamyz9VO_M_jNJBY_KHNrj/preview" },
    { "title": "GRAVITATION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1wBqCdOI88OXxaZh2ZlI5RDakeQpjid0t/preview" },
    { "title": "CIRCULAR MOTION SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1TyiO9kWPJOFP4ZhRhbtTxw-UC2ackqaX/preview" },
    { "title": "AC SOL", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/12WGLLwxX7ktTu69MN6Ycz-cbCmxfo0vL/preview" },
    { "title": "ALTERNATING CURRENT", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1RIIcikbMjNqQw_MvSpiSPVMDEzMBFyNK/preview" },
    { "title": "CIRCULAR MOTION", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1QGshntBl624U3kf7AkkvRFY7wZnxgsH4/preview" },
    { "title": "INTRODUCTION TO PHYSICS", "folders": ["IIT-JEE", "COACHINGS", "NUCLEUS Modules", "Nucleus Physics all material combined"], "url": "https://drive.google.com/file/d/1FFyk9X9eB2KVoQSEy68jGA4EU3AN8Pnv/preview" }
];